# Day-1 NumPy
Importing Numpy

In [2]:
import numpy as np


In [3]:
numbers=np.array([1,2,3,4,5,6])
print(numbers)

[1 2 3 4 5 6]


### Accessing Array Elements

In [4]:
arr=np.array([20,30,40,50])
print(arr[0]) #output is =20 becase index 0=20
print(arr[-1]) #output is 50 beacase index -1 start from end end=50
#so let see

20
50


In [5]:
#Another example negative indexing
arr1=np.array([334,554,3,445,665])
print(arr1[3]) # so index -2= 445 let see
print(arr1[-3]) # so index -3= 3 let see

445
3


In [6]:
#indexing an array
import numpy as np
arr = np.array([10,20,30,40,50])
print(arr[0]) #indexing
print(arr[2]) #indexing
print(arr[4]) #indexing

10
30
50


### Creating a 2D array

In [7]:
arr2=np.array([[22,12,33,44,55],[88,77,99,55,55]])
print(arr2)
print(type(arr2))

[[22 12 33 44 55]
 [88 77 99 55 55]]
<class 'numpy.ndarray'>


In [ ]:
#Another Example of 2D array
_2D=np.array([[23,44],[44,22]])
print(_2D)
print("Index 0,1=",_2D[0,1]) #Indexing

[[23 44]
 [44 22]]
Index 0,1= 44


### Zero Array

In [52]:
zero=np.zeros(5)
print(zero)

[0. 0. 0. 0. 0.]


In [53]:
zero=np.zeros(10)
print(zero)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [54]:
#Ones Array
Ones=np.ones(5)
print(Ones)

[1. 1. 1. 1. 1.]


In [55]:
Ones=np.ones(12)
print(Ones)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


### Arange

In [56]:
arange=np.arange(0,20)
print(arange)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [57]:
arange=np.arange(15) #if we give only one number then he start from zero to 14
print(arange)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [58]:
# Arange with Step 
arange=np.arange(0,20,2) #start from 0 end 20 and 2 is step 0,2,4 ...18
print(arange)

[ 0  2  4  6  8 10 12 14 16 18]


In [59]:
# Arange with Step 
arange=np.arange(0,20,3) #start from 0 end 20 and 3 is step 0,3,6,9,12 ...18
print(arange)

[ 0  3  6  9 12 15 18]


### 3d Array

In [60]:
_3d=np.array([[[3,4,5,6],[33,44,55,66]],[[77,66,77,88],[0,9,8,7]]])
print(_3d)
print(_3d[0,0,3]) #indexing 3D array index = 0 for [[3,4,5,6],[33,44,55,66]] then index=0 [3,4,5,6] and index 3 = 6

[[[ 3  4  5  6]
  [33 44 55 66]]

 [[77 66 77 88]
  [ 0  9  8  7]]]
6


In [61]:
simple_arr=np.array([]) #structer of creating array 
arr2=np.array([[],[]]) #this is the structer of 2D array
arr3=np.array([[[],[]],[[],[]]]) #this is the structer of 3d array

### Slicing

In [68]:
numbers=np.array([1,2,3,4,5,8]) # 3 to 8
print(numbers[2:6]) #yaha per start huwa hay index 2=3 awer end number hay index 6 jo k shumar nhi hotha to os se pehla number shumar hoga index 5=8

[3 4 5 8]


In [79]:
#Another example Reverse
numbers=np.array([1,2,3,4]) #4 to 1
print(numbers[::-1])#

[4 3 2 1]


In [87]:
# slicing with 2D array
arr2=np.array([[22,12,33,44,55],[88,77,99,55,55]])
print(arr2[0,0:3])
print(arr2[1,0:3])
print(arr2[0,::-1])
print(arr2[1,::-1])



[22 12 33]
[88 77 99]
[55 44 33 12 22]
[55 55 99 77 88]


### 3D array

In [ ]:
_3d=np.array([[[3,4,5,6],[33,44,55,66]],[[77,66,77,88],[0,9,8,7]]])
print(_3d[0,0,::-1])
print(_3d[0,1,::-1])
print(_3d[1,0,::-1])
print(_3d[1,1,::-1])


[6 5 4 3]
[66 55 44 33]
[88 77 66 77]
[7 8 9 0]
