### Importing Pyhton Library

In [1]:
import numpy as np

### Reshaping

In [ ]:
arr=np.array(["ishfaq","kashif","Wajid","Afaq","Mujahid","Ubaid"])
new_arr=arr.reshape(2,3) #Reshape into 2D array
print(arr)
print("\n",new_arr) 



['ishfaq' 'kashif' 'Wajid' 'Afaq' 'Mujahid' 'Ubaid']

 [['ishfaq' 'kashif' 'Wajid']
 ['Afaq' 'Mujahid' 'Ubaid']]


In [ ]:
arr=np.array(["ishfaq","kashif","Wajid","Afaq","Mujahid","Ubaid","Sajid","Majid"])
new_arr=arr.reshape(2,2,2) #Reshape into 3D array
print(arr)
print("\n",new_arr)



['ishfaq' 'kashif' 'Wajid' 'Afaq' 'Mujahid' 'Ubaid' 'Sajid' 'Majid']

 [[['ishfaq' 'kashif']
  ['Wajid' 'Afaq']]

 [['Mujahid' 'Ubaid']
  ['Sajid' 'Majid']]]


In [19]:
#Anothr Example 
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
new_arr=arr.reshape(2,2,3)
print(new_arr)
print("\n Index [1,1,1]= ",new_arr[1,1,1]) #Accessing 11 using index let see
print("\n Slicing [0,1,::-1]=",new_arr[0,1,::-1]) #Accessing 4,5,6 [0,1,::-1]= 6,5,4 using Slicing let see

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

 Index [1,1,1]=  11

 Slicing [0,1,::-1]= [6 5 4]


### -1 in reshape()
NumPy automatically calculates one dimension.

In [49]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
new_arr = arr.reshape(6,-1)
print(new_arr)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


### Flattening an Array

In [22]:
arr = np.array([
[1,2,3],
[4,5,6]
])
print("Multi dimensional array=\n",arr)
print("Flattening Array=",arr.flatten())

Multi dimensional array=
 [[1 2 3]
 [4 5 6]]
Flattening Array= [1 2 3 4 5 6]


In [ ]:
_3d=np.array([[[3,4,5,6],[33,44,55,66]],[[77,66,77,88],[0,9,8,7]]])
print(_3d)
#Flattening an Array
new_3d=_3d.flatten()
print("\n Flattening Array=",new_3d)
#Reshaping
reshap_3d=new_3d.reshape(2,2,4)
print("\n Reshape=",reshap_3d)

[[[ 3  4  5  6]
  [33 44 55 66]]

 [[77 66 77 88]
  [ 0  9  8  7]]]

 Flattening Array= [ 3  4  5  6 33 44 55 66 77 66 77 88  0  9  8  7]

 Reshape= [[[ 3  4  5  6]
  [33 44 55 66]]

 [[77 66 77 88]
  [ 0  9  8  7]]]


## Mathematical Operations

### Addition

In [30]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print("Addition a+b =",a + b)

Addition a+b = [5 7 9]


### Subtraction

In [32]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print("Subtraction a-b =",a - b)

Subtraction a-b = [-3 -3 -3]


### Multiplication

In [33]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print("Multiplication a*b =",a * b)

Multiplication a*b = [ 4 10 18]


### Division

In [34]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print("Division a/b =",a / b)

Division a/b = [0.25 0.4  0.5 ]


### Power

In [35]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print("Power a**b =",a ** b)

Power a**b = [  1  32 729]


### Square Root

In [36]:
arr = np.array([4,9,16,25])
print(np.sqrt(arr))

[2. 3. 4. 5.]


### Sum

In [37]:
arr = np.array([1,2,3,4])
print(np.sum(arr))

10


### Average (mean)

In [38]:
arr = np.array([1,2,3,4])
print(np.mean(arr))

2.5


### Maximum Value

In [39]:
arr = np.array([1,2,3,4])
print(np.max(arr))

4


### Minimum Value


In [40]:
arr = np.array([1,2,3,4])
print(np.min(arr))

1


### Standard Deviation

In [41]:
arr = np.array([1,2,3,4])
print(np.std(arr))

1.118033988749895


### Exponential

In [42]:
arr = np.array([1,2,3,4])
print(np.exp(arr))

[ 2.71828183  7.3890561  20.08553692 54.59815003]


### Logarithm

In [43]:
arr = np.array([1,2,3,4])
print(np.log(arr))

[0.         0.69314718 1.09861229 1.38629436]


### Trigonometric Functions

In [44]:
angles = np.array([0,30,45,60,90])
print(np.sin(np.radians(angles)))

[0.         0.5        0.70710678 0.8660254  1.        ]


### Average

In [53]:
arr = np.array([10,20,30,40,50])
print(np.average(arr))

30.0


### Variance

In [52]:
arr = np.array([10,20,30,40,50])
print(np.var(arr))

200.0
